name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 20 * * 1'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    ignore P/R 
    - uses: stale actions/stale@v3
      with:
        repo-token: has no access anymore
        stale-issue-message: 'Stale issue message'
        stale-issue-label: 'no-issue-activity'
